[package]
name = "conditions"
version = "0.1.3"
edition = "2021"
authors = ["John Allen <johnallen3d@threedogconsulting.com>"]
repository = "https://github.com/johnallen3d/conditions"
description = "Fetch basic weather conditions for current or specified location"
keywords = ["weather"]
categories = ["command-line-utilities"]
readme = "README.md"

license = "MIT"

[dependencies]
clap = { version = "4.4.2", features = ["derive"] }
confy = "0.5.1"
env_logger = "0.10.0"
eyre = "0.6.8"
lazy_static = "1.4.0"
log = "0.4.20"
serde = { version = "1", features = ["derive"] }
thiserror = "1.0.48"
ureq = { version = "2.7.1", features = ["json"] }
