[package]
name = "conditions"
version = "0.1.0"
edition = "2021"
authors = ["John Allen <johnallen3d@threedogconsulting.com>"]
description = "Fetch basic weather conditions for current location"

[dependencies]
clap = { version = "4.3.10", features = ["derive"] }
confy = "0.5.1"
env_logger = "0.10.0"
lazy_static = "1.4.0"
log = "0.4.19"
serde = { version = "1", features = ["derive"] }
thiserror = "1.0.43"
ureq = { version = "2.7.1", features = ["json"] }
