[package]
name = "conditions"
version = "0.1.0"
edition = "2021"
authors = ["John Allen <johnallen3d@threedogconsulting.com>"]
description = "Fetch basic weather conditions for current location"

[dependencies]
clap = { version = "4.1.8", features = ["derive"] }
confy = "0.5.1"
serde = { version = "1", features = ["derive"] }
ureq = { version = "2.6.2", features = ["json"] }
