name: ci

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: macos-latest
            features: sketchybar

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Setup Cache
        uses: Swatinem/rust-cache@v2

      - if: ${{ !matrix.features }}
        name: Build crate
        run: cargo build

      - if: ${{ matrix.features }}
        name: Build crate
        run: cargo build --features ${{ matrix.features }}

      - name: Run tests
        run: cargo test

      - name: Check formatting
        run: cargo fmt --all --check

      - name: Run clippy
        run: cargo clippy --all -- --deny clippy::pedantic
